#!/usr/bin/env python
import sys
import visualize
import experiment

if __name__ == '__main__':
    name = sys.argv[1]
    if len(sys.argv) >= 3:
        experiment_variant = sys.argv[2:]
    else:
        experiment_variant = None
    experiment = experiment.Experiment(name, experiment_variant)
    experiment.build_world()
    vis = visualize.Visualizer(experiment)
    vis.run()
